apiVersion: apps/v1
kind: Deployment
metadata:
  name: pythonweb08
  labels:
    app: pythonweb08
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pythonweb08
  template:
    metadata:
      labels:
        app: pythonweb08
    spec:
      containers:
      - name: pythonweb08
        image: chandana2025/pythonapp:v1
        ports:
        - containerPort: 5000
