apiVersion: v1
kind: Service
metadata:
  labels:
    app: pythonweb08
  name: pythonweb08
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: pythonweb08
